// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABwau1EploXBbn1Dcj4xZ0cqszZIKXfSM',
    appId: '1:118238915722:web:your-web-app-id',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    authDomain: 'mentorbridge-c5e60.firebaseapp.com',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    databaseURL: 'https://mentorbridge-c5e60-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABwau1EploXBbn1Dcj4xZ0cqszZIKXfSM',
    appId: '1:118238915722:android:your-android-app-id',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    databaseURL: 'https://mentorbridge-c5e60-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABwau1EploXBbn1Dcj4xZ0cqszZIKXfSM',
    appId: '1:118238915722:ios:f4c8db4d301f66f12d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    authDomain: 'mentorbridge-c5e60.firebaseapp.com',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    databaseURL: 'https://mentorbridge-c5e60-default-rtdb.firebaseio.com',
    iosClientId: '118238915722-qm6k9ki9k39orm2c1sgk1pm8sq7uv434.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABwau1EploXBbn1Dcj4xZ0cqszZIKXfSM',
    appId: '1:118238915722:ios:f4c8db4d301f66f12d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    authDomain: 'mentorbridge-c5e60.firebaseapp.com',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    databaseURL: 'https://mentorbridge-c5e60-default-rtdb.firebaseio.com',
    iosClientId: '118238915722-qm6k9ki9k39orm2c1sgk1pm8sq7uv434.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentorbridge',
  );
}