// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-4jX3ZSj7Gnpfmbukb-hPodve2bCoRQ',
    appId: '1:118238915722:web:1de5fc4c7589a9072d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    authDomain: 'mentorbridge-c5e60.firebaseapp.com',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    measurementId: 'G-3XEK5LDX58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FcRIPbpSWmv_SwzGN_XMoRA7rVDf8pY',
    appId: '1:118238915722:android:fcda2ad320620f782d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABwau1EploXBbn1Dcj4xZ0cqszZIKXfSM',
    appId: '1:118238915722:ios:f4c8db4d301f66f12d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    iosBundleId: 'com.example.mentorbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABwau1EploXBbn1Dcj4xZ0cqszZIKXfSM',
    appId: '1:118238915722:ios:f4c8db4d301f66f12d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    iosBundleId: 'com.example.mentorbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-4jX3ZSj7Gnpfmbukb-hPodve2bCoRQ',
    appId: '1:118238915722:web:801e1223b05620702d9173',
    messagingSenderId: '118238915722',
    projectId: 'mentorbridge-c5e60',
    authDomain: 'mentorbridge-c5e60.firebaseapp.com',
    storageBucket: 'mentorbridge-c5e60.firebasestorage.app',
    measurementId: 'G-N78FMM4CLE',
  );
}
